development:
  adapter: postgresql
  encoding: unicode
  database: not_twitter_development
  pool: 5
  username: marc
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: not_twitter_test
  pool: 5
  username: marc
  password:
cucumber:
  <<: *test